Repository Glauber-Developer/dot-sheet, pull requests merged in 2024-11, with the labels that each got.

#28 Feat/reporting service #16 #17 #18
  attendance_service/src/main/resources/application.properties
  build-images.sh
  reporting_service/src/main/java/com/reporting_service/reporting_service/controller/ReportingController.java
  reporting_service/src/main/java/com/reporting_service/reporting_service/domain/AttendanceReport.java
  reporting_service/src/main/java/com/reporting_service/reporting_service/repository/AttendanceReportRepository.java
  reporting_service/src/main/java/com/reporting_service/reporting_service/service/ReportingService.java
Labels: Reporting Service

#33 #19 #20 #21
  api_gateway/pom.xml
  api_gateway/src/main/java/com/api_gateway/api_gateway/ApiGatewayApplication.java
  api_gateway/src/main/java/com/api_gateway/api_gateway/filter/JwtAuthenticationFilter.java
  api_gateway/src/main/resources/application.properties
  docker-compose.yml
  eureka_server/pom.xml
  eureka_server/src/main/resources/application.properties
  reporting_service/pom.xml
  reporting_service/src/main/java/com/reporting_service/reporting_service/ReportingServiceApplication.java
  reporting_service/src/main/resources/application.properties
  user_service/pom.xml
  user_service/src/main/resources/application.properties
Labels: bug

#35 fix(payroll): fix eureka
  docker-compose.yml
  payroll_service/pom.xml
  payroll_service/src/main/java/com/payroll_service/payroll_service/PayrollServiceApplication.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/domain/User.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/repository/UserRepository.java
  payroll_service/src/main/resources/application.properties
Labels: bug

#36 fix(attendance): #19 #20 #21
  attendance_service/pom.xml
  attendance_service/src/main/resources/application.properties
  attendance_service/src/main/resources/data.sql
  docker-compose.yml
  image.png
Labels: bug

#37 #27
  README.md
  image.png
Labels: Infrastructure

#38 fix(clean): #19 #20 #21
  attendance_service/src/main/java/com/attendance_service/attendance_service/RabbitMQPublisher.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/controller/AttendanceController.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/infrastructure/repository/AttendanceRepository.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/modal/Attendance.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/model/Attendance.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/service/AttendanceService.java
  attendance_service/src/main/resources/data.sql
  attendance_service/src/test/java/com/attendance_service/attendance_service/AttendanceControllerTests.java
  attendance_service/src/test/java/com/attendance_service/attendance_service/AttendanceServiceTests.java
  user_service/src/main/java/com/user_service/user_service/app/controller/UserController.java
  user_service/src/main/java/com/user_service/user_service/app/service/UserService.java
  user_service/src/main/java/com/user_service/user_service/controller/UserController.java
  user_service/src/main/java/com/user_service/user_service/infrastructure/DataInitializer.java
  user_service/src/main/java/com/user_service/user_service/infrastructure/repository/UserRepository.java
  user_service/src/main/java/com/user_service/user_service/model/User.java
  user_service/src/main/java/com/user_service/user_service/repository/UserRepository.java
  user_service/src/main/java/com/user_service/user_service/service/UserService.java
Labels: bug

#39 fix(package): #19 #20 #21
  attendance_service/src/main/java/com/attendance_service/attendance_service/RabbitMQPublisher.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/app/controller/AttendanceController.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/app/service/AttendanceService.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/domain/Attendance.java
  attendance_service/src/main/java/com/attendance_service/attendance_service/infrastructure/repository/AttendanceRepository.java
  attendance_service/src/test/java/com/attendance_service/attendance_service/AttendanceControllerTests.java
  attendance_service/src/test/java/com/attendance_service/attendance_service/AttendanceServiceTests.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/app/service/PayrollService.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/client/AttendanceClient.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/client/UserClient.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/infrastructure/repository/UserRepository.java
  payroll_service/src/main/java/com/payroll_service/payroll_service/messaging/AttendanceEventListener.java
  reporting_service/src/main/java/com/reporting_service/reporting_service/app/controller/ReportingController.java
  reporting_service/src/main/java/com/reporting_service/reporting_service/app/service/ReportingService.java
  reporting_service/src/main/java/com/reporting_service/reporting_service/infrastructure/repository/AttendanceReportRepository.java
Labels: bug
